version: 2

projects:
 - name: "project-A"
   config:
     - type: "Default"
       path: "example/project-A/VERSION"
 - name: "project-B"
   config:
     - type: "Default"
       path: "example/project-B/VERSION"
     - type: "PackageJSON"
       path: "example/project-B/package.json"
